// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqhxLkH_ypGToQti2eEdMoTvYMxUerhTc',
    appId: '1:407553345842:android:dbb81b0c8af9cdaa0f6f2b',
    messagingSenderId: '407553345842',
    projectId: 'recipeapp-e4fdc',
    databaseURL: 'https://recipeapp-e4fdc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipeapp-e4fdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArcWuZ82sXjxLNOIaLkE6PEImrjHa4LVk',
    appId: '1:407553345842:ios:e276d935c94ae92e0f6f2b',
    messagingSenderId: '407553345842',
    projectId: 'recipeapp-e4fdc',
    databaseURL: 'https://recipeapp-e4fdc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipeapp-e4fdc.firebasestorage.app',
    iosClientId: '407553345842-uehck3rhbc32kbnvr404mpnjn58irtp6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASzGJdcAa5cac73TSSDjC1bO7bM1yr_3o',
    appId: '1:407553345842:web:af294983421440fc0f6f2b',
    messagingSenderId: '407553345842',
    projectId: 'recipeapp-e4fdc',
    authDomain: 'recipeapp-e4fdc.firebaseapp.com',
    databaseURL: 'https://recipeapp-e4fdc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'recipeapp-e4fdc.firebasestorage.app',
  );
}
